import { ConvexClient } from 'convex/browser';
import {
	type FunctionReference,
	type FunctionReturnType,
	type GenericDataModel
} from 'convex/server';
import { onDestroy } from 'svelte';

import { PUBLIC_CONVEX_URL } from '$env/static/public';

// Read from environment variables (Vite handles .env automatically)
// VITE_CONVEX_URL is usually generated by `npx convex dev` into .env.local
const convexUrl = PUBLIC_CONVEX_URL;

if (!convexUrl) {
	console.error('PUBLIC_CONVEX_URL is not defined. Make sure you have run `bunx convex dev`.');
}

export const convex = new ConvexClient(convexUrl);

/**
 * A reactive Convex query helper for Svelte 5 (Runes).
 * @param query The Convex query function.
 * @param args The arguments for the query.
 * @returns An object with `data` property that updates automatically.
 */
export function createQuery<Query extends FunctionReference<'query'>>(
	query: Query,
	args: () => any
) {
	let data = $state<FunctionReturnType<Query> | undefined>(undefined);
	let isLoading = $state(true);
	let error = $state<Error | undefined>(undefined);

	$effect(() => {
		const currentArgs = args();

		// Subscribe to the query
		const unsubscribe = convex.onUpdate(query, currentArgs, (result) => {
			data = result;
			isLoading = false;
		});

		return () => {
			unsubscribe();
		};
	});

	return {
		get data() {
			return data;
		},
		get isLoading() {
			return isLoading;
		},
		get error() {
			return error;
		}
	};
}
